branches:
  - master
  - name: beta
    prerelease: true
    channel: beta
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
